### ISSUE TITLE
pytz in setup.py

### ISSUE THREAD

**Issue by Potemkinkuliss** [costerwi/dwdatareader#36]
I think you are missing pytz in the requirements.
```
Traceback (most recent call last):
    print(f.info)
  File "[...]/python3.8/site-packages/dwdatareader/__init__.py", line 44, in __str__
    return "{0.start_store_time} {0.sample_rate} Hz {0.duration} s".format(self)
  File "[...]/python3.8/site-packages/dwdatareader/__init__.py", line 50, in start_store_time
    import pytz
ModuleNotFoundError: No module named 'pytz'
```
I tested it with pytz==2021.1
To auto install add
install_requires=["pytz==2021.1"]
into the setup.py setup kwargs.

**Comment by Potemkinkuliss** [comment]
Pandas, numpy and matplotlib are also missing. I successfully tested using:
matplotlib==3.4.2
numpy==1.21.1
pandas==1.3.0

**Comment by costerwi** [comment]
Thanks for your comments.

I had previously considered those to be recommended modules but not strictly requirements since you may use some basic functions of this this module which do not require any of those others. I'm certainly open to reconsider that philosophy. That said, it looks like at least the [extras_require](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies) argument should be added to specify these modules.
